app/entrees/forms.py
# forms.py
# défini les formulaires de l'application en lien avec les entrées
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, DecimalField, DateField, SelectField
from wtforms.validators import NumberRange, ValidationError, DataRequired, Email, Length
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from flask_babel import _, lazy_gettext as _l
from datetime import date
from app.models import Contact, CompanyProfil, Compte
import re
from flask_login import current_user

# Défini un formulaire pour la saisie de factures
class FactureForm(FlaskForm):
    # À ajouter des attributs
    paid = SelectField('', choices=[(0, _l('Impayée')), (1, _l('Payée'))], coerce=int)
    reference = StringField(_l('Référence'), validators=[DataRequired(message=_l("Veuillez entrer une référence")), Length(min=1, max=50, message=_l('Veuillez écrire entre 1 et 50 caractères'))])
    date = DateField(_l('Date'), default=date.today(), format='%Y-%m-%d', validators=[DataRequired(message=_l("Veuillez entrer une date (AAAA-MM-JJ)"))])
    due_date = DateField(_l('Date d\'échéance'), format='%Y-%m-%d', validators=[DataRequired(message=_l("Veuillez entrer une date d'échéance (AAAA-MM-JJ)"))])
    description = TextAreaField(_l('Description'), validators=[DataRequired(message=_l("Veuillez entrer une description")), Length(min=1, max=140, message=_l(_l('Veuillez écrire entre 1 et 140 caractères')))])
    subtotal = DecimalField(_l('Sous-total'), validators=[DataRequired(message=_l("Veuillez entrer un montant numérique"))], places=2)
    tax = DecimalField(_l('Taxe (%)'), default=14.975, validators=[NumberRange(0, 100, _l("Veuillez entrer un nombre entre 0 et 100"))], places=3)

    # Query qui get tous les contacts de l'utilisateur actif
    def get_contacts():
        return Contact.query.filter_by(user_id=current_user.id)

    contact_id = QuerySelectField(_l('Contact ID'), validators=[DataRequired(message=_l('Veuillez entrer un contact'))], query_factory=get_contacts, get_label="name", allow_blank=True)

    # Query qui get tous les comptes de l'utilisateur actif
    def get_comptes():
        return Compte.query.filter_by(user_id=current_user.id)

    compte_id = QuerySelectField(_l('Compte ID'), validators=[DataRequired(message=_l('Veuillez entrer un compte'))], query_factory=get_comptes, get_label="name", allow_blank=True)

    submit = SubmitField(_l('Enregistrer'))

    # Valider si date d'échéance est la même ou après la date initiale
    def validate_due_date(self, due_date):
        if due_date.data < self.date.data:
            raise ValidationError(_l('La date d\'échéance doit être la même ou après la date initale'))

    # Get le montant total après taxes en arrondissant à 2 décimals
    @staticmethod
    def get_total(tax, sub_total):
        return round((sub_total * (tax + 100) / 100), 2)

# Défini un formulaire pour la saisie de contacts
class ContactForm(FlaskForm):
    # Validation à améliorer
    name = StringField(_l('Nom'), validators=[DataRequired(message=_l("Veuillez entrer un nom")), Length(min=1, max=50, message=_l('Veuillez écrire entre 1 et 50 caractères'))])
    phone_number = StringField(_l('Téléphone'), [DataRequired(Length(min=12, max=12, message=_l('Veuillez entrer un numéro de téléphone (123-456-7890)')))])
    email = StringField(_l('Adresse courriel'), validators=[DataRequired(message=_l('Veuillez entrer une adresse courriel valide')), Email(message=_l('Veuillez entrer une adresse courriel valide'))])
    address = TextAreaField(_l('Adresse'), validators=[DataRequired(message=_l("Veuillez entrer une adresse")), Length(min=1, max=140, message=_l(_l('Veuillez écrire entre 1 et 140 caractères')))])
    submit = SubmitField(_l('Enregistrer'))

    def validate_phone_number(self, phone_number):
        phone_number = phone_number.data
        pattern = "^\d{3}-\d{3}-\d{4}$"
        match = re.search(pattern, phone_number)
        if not match:
            raise ValidationError(_l('Veuillez entrer un numéro de téléphone valide (123-456-7890)'))

# Défini un formulaire pour la saisie de comptes
class CompteForm(FlaskForm):
    name = StringField(_l('Nom'), validators=[DataRequired(message=_l("Veuillez entrer un nom")), Length(min=1, max=50, message=_l('Veuillez écrire entre 1 et 50 caractères'))])
    submit = SubmitField(_l('Enregistrer'))

# Défini un formulaire pour la profil d'entreprise
class CompanyProfilForm(FlaskForm):
    # Validation à améliorer
    name = StringField(_l('Nom'), validators=[DataRequired(message=_l("Veuillez entrer un nom")), Length(min=1, max=50, message=_l('Veuillez écrire entre 1 et 50 caractères'))])
    submit = SubmitField(_l('Enregistrer'))

# Défini un formulaire de sélection de profil d'entreprise
class SelectCompanyProfilForm(FlaskForm):
    # Query qui get tous les contacts de l'utilisateur actif
    def get_company_profil():
        return CompanyProfil.query.filter_by(user_id=current_user.id)

    company_profil_name = QuerySelectField(_l('Nom de l\'entreprise'), validators=[DataRequired(message=_l('Veuillez choisir un profil d\'entreprise'))], query_factory=get_company_profil, get_label="name", allow_blank=False)
    submit = SubmitField(_l('Sélectionner'))
    

app/entrees/__init__.py
# __init__.py
# défini le blueprint du core de l'application
from flask import Blueprint

bp = Blueprint('entrees', __name__)

from app.entrees import routes

app/entrees/routes.py
# routes.py
# défini les routes de l'application en lien avec les entrées
from datetime import date
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required
from app import app, db
from app.entrees import bp
from app.entrees.forms import FactureForm, ContactForm, CompanyProfilForm, SelectCompanyProfilForm, CompteForm
from app.models import User, Facture, Contact, CompanyProfil, Compte
from flask_babel import _

# Page d'accueil pour les utilisateurs - page pour choisir les profils d'entreprise
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = SelectCompanyProfilForm()
    if form.validate_on_submit():
        companyProfil = CompanyProfil.query.filter_by(name=form.company_profil_name.data.name).first()
        if companyProfil:
            user_to_update = User.query.get_or_404(current_user.id)
            user_to_update.profil_courrant = companyProfil.id
            db.session.commit()
            flash(_('Vous avez sélectionné ' + companyProfil.name))
        else:
            companyProfil = CompanyProfil(name=form.company_profil_name.data, user_id=current_user.id)
            flash(_('Erreur. Profil d\'entreprise non trouvé.'))
            return redirect(url_for('entrees.index'))

    page = request.args.get('page', 1, type=int)

    # Tous les profils d'entreprise de l'utilisateur actuel
    companyProfil = CompanyProfil.query.filter_by(user_id=current_user.id).paginate(page, app.config['COMPANY_PROFIL_PAR_PAGE'], False)
    next_url = url_for('entrees.index', page=companyProfil.next_num) if companyProfil.has_next else None
    prev_url = url_for('entrees.index', page=companyProfil.prev_num) if companyProfil.has_prev else None
    return render_template("entrees/index.html", title=_('Accueil'), form=form, companyProfil=companyProfil.items, next_url=next_url, prev_url=prev_url)

# Page d'ajout de profil d'entreprise
@bp.route('/register_company_profil', methods=['GET', 'POST'])
@login_required
def register_company_profil():
    form = CompanyProfilForm()

    if form.validate_on_submit():
        companyProfil = CompanyProfil.query.filter_by(name=form.name.data).first()
        if companyProfil:
            flash(_('Ce profil d\'entreprise existe déjà.'))
        else:
            companyProfil = CompanyProfil(name=form.name.data, user_id=current_user.id)
            db.session.add(companyProfil)
            db.session.commit()
            flash(_('Votre profile d\'entreprise a été ajouté.'))
            return redirect(url_for('entrees.index'))
    
    page = request.args.get('page', 1, type=int)
    companyProfil = CompanyProfil.query.filter_by(user_id=current_user.id).paginate(page, app.config['COMPANY_PROFIL_PAR_PAGE'], False)
    next_url = url_for('entrees.register_company_profil', page=companyProfil.next_num) if companyProfil.has_next else None
    prev_url = url_for('entrees.register_company_profil', page=companyProfil.prev_num) if companyProfil.has_prev else None
    return render_template("entrees/register_company_profil.html", title=_('Accueil'), companyProfil=companyProfil.items, form=form, next_url=next_url, prev_url=prev_url)

# Page de création de factures
@bp.route('/bill', methods=['GET', 'POST'])
@login_required
def bill():
    if current_user.profilEntreprise:
        form = FactureForm()
        form.contact_id.choices = [''] + [(row.name) for row in Contact.query.filter_by(user_id=current_user.id)]
        # À ajouter des attributs
        if form.validate_on_submit():
            facture = Facture.query.filter_by(reference=form.reference.data).first()
            if facture:
                flash(_('Cette référence existe déjà.'))
            else:
                facture = Facture(paid=form.paid.data, reference=form.reference.data, date=form.date.data, due_date=form.due_date.data, description=form.description.data, contact_id=form.contact_id.data.id, compte_id=form.compte_id.data.id, profilEntreprise_id=current_user.profil_courrant, subtotal=form.subtotal.data, total=form.get_total(form.tax.data, form.subtotal.data), tax=form.tax.data, user_id=current_user.id)
                db.session.add(facture)
                db.session.commit()
                flash(_('Votre facture a été ajoutée.'))
                return redirect(url_for('entrees.bill'))

        # Toutes les factures de l'utilisateur actuel et du profil d'entreprise actuel
        page = request.args.get('page', 1, type=int)
        factures = Facture.query.filter_by(user_id=current_user.id, profilEntreprise_id=current_user.profil_courrant).paginate(page, app.config['FACTURES_PAR_PAGE'], False)
        next_url = url_for('entrees.bill', page=factures.next_num) if factures.has_next else None
        prev_url = url_for('entrees.bill', page=factures.prev_num) if factures.has_prev else None
        return render_template("entrees/bill.html", title=_('Facture'), form=form, factures=factures.items, date_today=date.today(), next_url=next_url, prev_url=prev_url)
    else:
        flash(_('Veuillez créer un profil d\'entreprise avant d\'effectuer cette action.'))
        return redirect(url_for('entrees.index'))

# Page des contacts
@bp.route('/contacts', methods=['GET', 'POST'])
@login_required
def contacts():
    if current_user.profilEntreprise:
        form = ContactForm()
        if form.validate_on_submit():
            contact = Contact.query.filter_by(name=form.name.data, profilEntreprise_id=current_user.profil_courrant).first()
            if contact:
                flash(_('Ce contact existe déjà.'))
            else:
                contact = Contact(name=form.name.data, phone_number=form.phone_number.data, email=form.email.data, address=form.address.data, user_id=current_user.id, profilEntreprise_id=current_user.profil_courrant)
                db.session.add(contact)
                db.session.commit()
                flash(_('Votre contact a été ajouté.'))
                return redirect(url_for('entrees.contacts'))

        # Tous les contacts de l'utilisateur actuel
        page = request.args.get('page', 1, type=int)
        contacts = Contact.query.filter_by(user_id=current_user.id, profilEntreprise_id=current_user.profil_courrant).paginate(page, app.config['CONTACTS_PAR_PAGE'], False)
        next_url = url_for('entrees.contacts', page=contacts.next_num) if contacts.has_next else None
        prev_url = url_for('entrees.contacts', page=contacts.prev_num) if contacts.has_prev else None
        return render_template("entrees/contacts.html", title=_('Contacts'), form=form, contacts=contacts.items, next_url=next_url, prev_url=prev_url)
    else:
        flash(_('Veuillez créer un profil d\'entreprise avant d\'effectuer cette action.'))
        return redirect(url_for('entrees.index'))

# Page des comptes
@bp.route('/comptes', methods=['GET', 'POST'])
@login_required
def comptes():
    if current_user.profilEntreprise:
        form = CompteForm()
        if form.validate_on_submit():
            compte = Compte.query.filter_by(name=form.name.data, profilEntreprise_id=current_user.profil_courrant).first()
            if compte:
                flash(_('Ce compte existe déjà.'))
            else:
                compte = Compte(name=form.name.data, user_id=current_user.id, profilEntreprise_id=current_user.profil_courrant)
                db.session.add(compte)
                db.session.commit()
                flash(_('Votre compte a été ajouté.'))
                return redirect(url_for('entrees.comptes'))

        # Tous les comptes de l'utilisateur actuel
        page = request.args.get('page', 1, type=int)
        comptes = Compte.query.filter_by(user_id=current_user.id, profilEntreprise_id=current_user.profil_courrant).paginate(page, app.config['COMPTES_PAR_PAGE'], False)
        next_url = url_for('entrees.comptes', page=comptes.next_num) if comptes.has_next else None
        prev_url = url_for('entrees.comptes', page=comptes.prev_num) if comptes.has_prev else None
        return render_template("entrees/comptes.html", title=_('Comptes'), form=form, comptes=comptes.items, next_url=next_url, prev_url=prev_url)
    else:
        flash(_('Veuillez créer un profil d\'entreprise avant d\'effectuer cette action.'))
        return redirect(url_for('entrees.index'))

# Supprimer des factures
@bp.route('/delete_bill/<facture_id>')
@login_required
def delete_bill(facture_id):
    facture_to_delete = Facture.query.get_or_404(facture_id)
    try:
        db.session.delete(facture_to_delete)
        db.session.commit()
        return redirect(url_for('entrees.bill'))
    except Exception:
        error_string = _('Il y a eu une erreur avec la suppression de la facture.')
        return render_template('errors/error.html', title=_('Erreur'), error=error_string)

# Supprimer des contacts
@bp.route('/delete_contact/<contact_id>')
@login_required
def delete_contact(contact_id):
    contact_to_delete = Contact.query.get_or_404(contact_id)
    try:
        db.session.delete(contact_to_delete)
        db.session.commit()
        return redirect(url_for('entrees.contacts'))
    except Exception:
        error_string = _('Il y a eu une erreur avec la suppression du contact.')
        return render_template('errors/error.html', title=_('Erreur'), error=error_string)

# Supprimer des comptes
@bp.route('/delete_compte/<compte_id>')
@login_required
def delete_compte(compte_id):
    compte_to_delete = Compte.query.get_or_404(compte_id)
    try:
        db.session.delete(compte_to_delete)
        db.session.commit()
        return redirect(url_for('entrees.comptes'))
    except Exception:
        error_string = _('Il y a eu une erreur avec la suppression du compte.')
        return render_template('errors/error.html', title=_('Erreur'), error=error_string)


app/templates/entrees/bill.html
<!-- index.html -->
<!-- page d'accueil pour les utilisateurs -->
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Enregistrer une facture') }}</h1>
    <hr>
    {% if form %}
        <div class="form-group">
            <div class="col-md-4">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
        <hr>
    {% endif %}
    <!-- Affichage des factures -->
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">{{ _('Référence') }}</th>
            <th scope="col">{{ _('Description') }}</th>
            <th scope="col">{{ _('Contact ID') }}</th>
            <th scope="col">{{ _('Date') }}</th>
            <th scope="col">{{ _('Date d\'échéance') }}</th>
            <th scope="col">{{ _('Sous-total') }} ($)</th>
            <th scope="col">{{ _('Taxe') }} (%)</th>
            <th scope="col">{{ _('Total') }} ($)</th>
            <th scope="col">{{ _('Statut') }}</th>
            <th scope="col">{{ _('Options') }}</th>
          </tr>
        </thead>
        <tbody>
    {% for facture in factures %}
        <!-- Valide l'état de la facture -->
        {% if facture.paid %}
            {% set facture_state = _('Payée') %}
        {% else %}
            {% set facture_state = _('Impayée') %}
            <!-- Valide si la date d'échéance est dépassée alors qu'elle est impayée -->
            {% if facture.due_date <= date_today%}
                {% set date_state = 'past-due' %}
            {% endif %}
        {% endif %}
        <!-- Corps des factures -->
        <tr>
            <!-- À ajouter des attributs -->
            <td>{{ facture.reference }}</td>
            <td>{{ facture.description }}</td>
            <td>{{ facture.contact_id }}</td>
            <td>{{ facture.date }}</td>
            <td class="{{ date_state }}">{{ facture.due_date }}</td>
            <td>{{ facture.subtotal }}</td>
            <td>{{ facture.tax }}</td>
            <td>{{ facture.total }}</td>
            <td class="{{ date_state }}">{{ facture_state }}</td>
            <td>
                <a class="btn btn-info" href="{{ url_for('entrees.update_bill', facture_id=facture.id) }}">{{ _('Modifier') }}</a>
                <a class="btn btn-danger" href="{{ url_for('entrees.delete_bill', facture_id=facture.id) }}">{{ _('Supprimer') }}</a>
            </td>
        </tr>
    {% endfor %}
        </tbody>
    </table>
    <!-- Pagination -->
    {% if prev_url %}
        <a class="btn btn-link" href="{{ prev_url }}">{{ _('Page précédente') }}</a>
    {% endif %}
    {% if next_url %}
        <a class="btn btn-link" href="{{ next_url }}">{{ _('Page suivante') }}</a>
    {% endif %}
    <br><br>
{% endblock %}

app/templates/entrees/comptes.html
<!-- comptes.html -->
<!-- page comptes pour les utilisateurs -->
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Enregistrer un compte') }}</h1>
    <hr>
    {% if form %}
        <div class="form-group">
            <div class="col-md-4">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
        <hr>
    {% endif %}
    <!-- Affichage des comptes -->
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">{{ _('Nom') }}</th>
            <th scope="col">{{ _('Options') }}</th>
          </tr>
        </thead>
        <tbody>
    {% for compte in comptes %}
        <!-- Corps des comptes -->
        <tr>
            <!-- À ajouter des attributs -->
            <td>{{ compte.id }}</td>
            <td>{{ compte.name }}</td>
            <td>
                <a class="btn btn-info" href="{{ url_for('entrees.update_compte', compte_id=compte.id) }}">{{ _('Modifier') }}</a>
                <a class="btn btn-danger" href="{{ url_for('entrees.delete_compte', compte_id=compte.id) }}">{{ _('Supprimer') }}</a>
            </td>
        </tr>
    {% endfor %}
        </tbody>
    </table>
    <!-- Pagination -->
    {% if prev_url %}
        <a class="btn btn-link" href="{{ prev_url }}">{{ _('Page précédente') }}</a>
    {% endif %}
    {% if next_url %}
        <a class="btn btn-link" href="{{ next_url }}">{{ _('Page suivante') }}</a>
    {% endif %}
    <br><br>
{% endblock %}

app/templates/entrees/contacts.html
<!-- contacts.html -->
<!-- page contacts pour les utilisateurs -->
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Enregistrer un contact') }}</h1>
    <hr>
    {% if form %}
        <div class="form-group">
            <div class="col-md-4">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
        <hr>
    {% endif %}
    <!-- Affichage des contacts -->
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">{{ _('Nom') }}</th>
            <th scope="col">{{ _('Téléphone') }}</th>
            <th scope="col">{{ _('Adresse courriel') }}</th>
            <th scope="col">{{ _('Adresse') }}</th>
            <th scope="col">{{ _('Options') }}</th>
          </tr>
        </thead>
        <tbody>
    {% for contact in contacts %}
        <!-- Corps des contacts -->
        <tr>
            <!-- À ajouter des attributs -->
            <td>{{ contact.id }}</td>
            <td>{{ contact.name }}</td>
            <td>{{ contact.phone_number }}</td>
            <td>{{ contact.email }}</td>
            <td>{{ contact.address }}</td>
            <td>
                <a class="btn btn-info" href="{{ url_for('entrees.update_contact', contact_id=contact.id) }}">{{ _('Modifier') }}</a>
                <a class="btn btn-danger" href="{{ url_for('entrees.delete_contact', contact_id=contact.id) }}">{{ _('Supprimer') }}</a>
            </td>
        </tr>
    {% endfor %}
        </tbody>
    </table>
    <!-- Pagination -->
    {% if prev_url %}
        <a class="btn btn-link" href="{{ prev_url }}">{{ _('Page précédente') }}</a>
    {% endif %}
    {% if next_url %}
        <a class="btn btn-link" href="{{ next_url }}">{{ _('Page suivante') }}</a>
    {% endif %}
    <br><br>
{% endblock %}

app/templates/entrees/index.html
<!-- index.html -->
<!-- page de sélection des profils d'entreprise -->
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Vos profils d\'entreprise') }}</h1>
    <hr>
    {% if companyProfil|length > 0 %}
        <h3>{{ _('Sélectionner votre entreprise') }}</h3>
        {% if form %}
            <div class="form-group">
                <div class="col-md-4">
                    {{ wtf.quick_form(form) }}
                </div>
            </div>
            <hr>
        {% endif %}

        <a href="{{ url_for('entrees.register_company_profil') }}">
            <span>
                {{ _('Gérer vos profil d\'entreprise') }}
            </span>
        </a>

    {% else %}
        <h2>{{ _('Vous n\'avez pas de profil d\'entreprise') }}</h2>
        <a href="{{ url_for('entrees.register_company_profil') }}">
            <span>
                {{ _('Ajouter un profil d\'entreprise') }}
            </span>
        </a>
    {% endif %}
    
{% endblock %}

app/templates/entrees/register_company_profil.html
<!-- login.html -->
<!-- page de connexion pour les utilisateurs -->
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Enregistrer un profil d\'entreprise') }}</h1>
    <!-- Form pour se connecter a l'application -->
    <hr>
    {% if form %}
        <div class="form-group">
            <div class="col-md-4">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
        <hr>
    {% endif %}
    <!-- Affichage des contacts -->
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">{{ _('Nom') }}</th>
            <th scope="col">{{ _('Options') }}</th>
          </tr>
        </thead>
        <tbody>
    {% for company_profil in companyProfil %}
        <!-- Corps des contacts -->
        <tr>
            <!-- À ajouter des attributs -->
            <td>{{ company_profil.id }}</td>
            <td>{{ company_profil.name }}</td>
            <td>
                <a class="btn btn-info" href="{{ url_for('entrees.update_company_profil', company_profil_id=company_profil.id) }}">{{ _('Modifier') }}</a>
                <a class="btn btn-danger" href="{{ url_for('entrees.delete_company_profil', company_profil_id=company_profil.id) }}">{{ _('Supprimer') }}</a>
            </td>
        </tr>
    {% endfor %}
        </tbody>
    </table>
    <!-- Pagination -->
    {% if prev_url %}
        <a class="btn btn-link" href="{{ prev_url }}">{{ _('Page précédente') }}</a>
    {% endif %}
    {% if next_url %}
        <a class="btn btn-link" href="{{ next_url }}">{{ _('Page suivante') }}</a>
    {% endif %}
    <br><br>

{% endblock %}

app/templates/entrees/update_company_profil.html
<!-- update_company_profil.html -->
<!-- page de modification des profils d'entreprise -->
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Modifier le profil d\'entreprise') }} <em>{{ company_profile.name }}</em></h1>
    <hr>
    <div class="form-group">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div> 
    </div>
{% endblock %}

app/templates/entrees/update_compte.html
<!-- update_compte.html -->
<!-- page de modification des comptes -->
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Modifier le compte') }} <em>{{ compte.name }}</em></h1>
    <hr>
    <div class="form-group">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/entrees/update_contact.html
<!-- update_contact.html -->
<!-- page de modification des contacts -->
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Modifier le contact') }} <em>{{ contact.name }}</em></h1>
    <hr>
    <div class="form-group">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/entrees/update_facture.html
<!-- update_facture.html -->
<!-- page de modification des factures -->
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Modifier la facture') }} <em>{{ facture.reference }}</em></h1>
    <hr>
    <div class="form-group">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}