app/user/forms.py
# forms.py
# défini les formulaires en lien avec les utilisateurs
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length
from flask_babel import _, lazy_gettext as _l
from app.models import User

# Modifier le profil de l'utilisateur
class EditProfileForm(FlaskForm):
    username = StringField(_l('Utilisateur'), validators=[DataRequired(message=_l("Veuillez saisir un nom d'utilisateur"))])
    about_me = TextAreaField(_l('À propos de moi'), validators=[Length(min=0, max=140)])
    submit = SubmitField(_l('Enregistrer'))

    # @Override du constructeur. Il a maintenant comme argument le original_username=current_user.username
    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    # Valider si l'utilisateur existe déjà
    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError(_l('Ce nom d\'utilisateur est déjà utilisé'))

app/user/__init__.py
# __init__.py
# défini le blueprint des utilisateurs
from flask import Blueprint

bp = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
# routes.py
# défini les routes de l'application en lien avec les utilisateurs
from datetime import date, datetime
from flask import render_template, flash, redirect, url_for, request, session
from flask_login import logout_user, current_user, login_required
from app import app, db
from app.user import bp
from app.user.forms import EditProfileForm
from app.models import User, Facture
from flask_babel import _

# Page profil
@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user/user.html', title=_('Mon profil'), user=user)

# Supprimer un utilisateur et toutes ses factures
@bp.route('/delete_user/<username>')
@login_required
def delete_user(username):
    try:
        user = User.query.filter_by(username=username).first_or_404()
        factures = Facture.query.filter_by(user_id=user.id).all()
        for f in factures:
            db.session.delete(f)
        logout_user()
        db.session.delete(user)
        db.session.commit()
        return redirect(url_for('welcome'))
    except:
        error_string = _('Il y a eu une erreur avec la suppression de l\'utilisateur.')
        return render_template('errors/error.html', title=_('Erreur'), error=error_string)
        
# Modifier son profil
@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    try:
        form = EditProfileForm(current_user.username)
        if form.validate_on_submit():
            current_user.username = form.username.data
            current_user.about_me = form.about_me.data
            db.session.commit()
            flash(_('Les modifications ont été sauvegardées.'))
            return redirect(url_for('user.user', username=current_user.username))
        elif request.method == 'GET':
            form.username.data = current_user.username
            form.about_me.data = current_user.about_me
        return render_template('user/edit_profile.html', title=_('Modifier votre profil'),form=form)
    except:
        error_string = _('Il y a eu une erreur avec la modification du profil.')
        return render_template('errors/error.html', title=_('Erreur'), error=error_string)

app/templates/user/edit_profile.html
<!-- edit_profile.html -->
<!-- page d'édition du profil de l'utilisateur courant -->
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Modifier le profil') }}</h1>
    <div class="form-group">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/user/user.html
<!-- user.html -->
<!-- page profil de l'utilisateur courant -->
{% extends "base.html" %}

{% block app_content %}
    <table>
        <!-- Body du profil -->
        <tr valign="top">
            <td><img src="{{ user.avatar(128) }}"></td>
            <td>
                <h1>{{ _("Profil de l'utilisateur") }} <strong>{{ user.username }}</strong></h1>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}<p>{{ _('Dernière connexion') }}: {{ moment(user.last_seen).format('LLL') }}</p>{% endif %}

                {% if user == current_user %}
                <p><a href="{{ url_for('user.edit_profile') }}">{{ _('Modifier votre profil') }}</a></p>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>
                <a href="{{ url_for('user.delete_user', username=current_user.username) }}">{{ _('Supprimer le compte') }}</a>
            </td>
        </tr>
    </table>
{% endblock %}